name: Java Gradle CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: 17

    - name: Setup CI Environment
      run: |
        echo "mod_ver=$(grep -F 'mod_version' gradle.properties | head -n 1 | awk -F '=' '{print $NF}')" >> "$GITHUB_ENV"
        echo "sha_short=$(git rev-parse --short ${{github.sha}})" >> "$GITHUB_ENV"
        # sed -i '/org.gradle.java.home/d' gradle.properties
        chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Release artifact
      uses: actions/upload-artifact@v4
      with:
        name: fmod-${{env.mod_ver}}-${{env.sha_short}}
        path: build/libs/fminecraftmod*.jar
